### ISSUE TITLE
Créer le module Map

### ISSUE THREAD

**Issue by techerjeansebastienpro** [steimbeck/bike#5]
https://github.com/steimbeck/bike/blob/8d375ff4108561bf9c385abdcf4ec062492164ee/JS/map.js#L1#L20

**sous forme d'objet**

Une classe MapController:
- qui fait appel au données d'api (utiliser `fetch()`)
- qui construit une instance de mapView
- qui render la mapView avec la liste des stations

```javascript
class MapController {} 
```

Une classe MapView :
- une méthode render qui affiche la map, et ajoute les marqueurs selon les positions des stations
```javascript
class MapView {}
```

**Comment by steimbeck** [comment]
done
